apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-frontend
  labels:
    app: otel-frontend
    version: 1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-frontend
  template:
    metadata:
      labels:
        app: otel-frontend
    spec:
      containers:
      - name: otel-frontend
        image: scoof/otel-frontend:1
        imagePullPolicy: Always
